[package]
name = "gh-action-security-scanner"
version = "0.1.0"
edition = "2024"
description = "A GitHub Action that scans workflow dependencies in workflows for vulnerabilities"
license = "Apache 2.0"
repository = "https://github.com/org/dependency-scanner"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
structopt = "0.3"
regex = "1.11.1"  
